apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-registry
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-registry
subjects:
- kind: ServiceAccount
  name: account-srv
  namespace: default
- kind: ServiceAccount
  name: account-api
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-api #重点
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeter-srv
    spec:
       #重点
      serviceAccountName: greeter-srv
      containers:
        - name: greeter
          image: microhq/greeter-srv:kubernetes
          command: [
                "/greeter-srv",
                "--server_address=0.0.0.0:8080",
                "--broker_address=0.0.0.0:10001"
          ]
          ports:
          - containerPort: 8080
            name: greeter-port
